/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as CvRouteImport } from './routes/cv'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearchPortfolioCensoredRouteImport } from './routes/research.portfolio-censored'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchPortfolioCensoredRoute =
  ResearchPortfolioCensoredRouteImport.update({
    id: '/portfolio-censored',
    path: '/portfolio-censored',
    getParentRoute: () => ResearchRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/experience': typeof ExperienceRoute
  '/research': typeof ResearchRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/research/portfolio-censored': typeof ResearchPortfolioCensoredRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/experience': typeof ExperienceRoute
  '/research': typeof ResearchRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/research/portfolio-censored': typeof ResearchPortfolioCensoredRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/experience': typeof ExperienceRoute
  '/research': typeof ResearchRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/research/portfolio-censored': typeof ResearchPortfolioCensoredRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cv'
    | '/experience'
    | '/research'
    | '/sitemap.xml'
    | '/research/portfolio-censored'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cv'
    | '/experience'
    | '/research'
    | '/sitemap.xml'
    | '/research/portfolio-censored'
  id:
    | '__root__'
    | '/'
    | '/cv'
    | '/experience'
    | '/research'
    | '/sitemap.xml'
    | '/research/portfolio-censored'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CvRoute: typeof CvRoute
  ExperienceRoute: typeof ExperienceRoute
  ResearchRoute: typeof ResearchRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/portfolio-censored': {
      id: '/research/portfolio-censored'
      path: '/portfolio-censored'
      fullPath: '/research/portfolio-censored'
      preLoaderRoute: typeof ResearchPortfolioCensoredRouteImport
      parentRoute: typeof ResearchRoute
    }
  }
}

interface ResearchRouteChildren {
  ResearchPortfolioCensoredRoute: typeof ResearchPortfolioCensoredRoute
}

const ResearchRouteChildren: ResearchRouteChildren = {
  ResearchPortfolioCensoredRoute: ResearchPortfolioCensoredRoute,
}

const ResearchRouteWithChildren = ResearchRoute._addFileChildren(
  ResearchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CvRoute: CvRoute,
  ExperienceRoute: ExperienceRoute,
  ResearchRoute: ResearchRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
